### ISSUE TITLE
Update broken links from spreadsheet

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/metadata#18]
https://docs.google.com/spreadsheets/d/1Al9y3IaXVKbnDGnO4po6uejrzNGmMVuXYopRn2L2iWU/edit#gid=1816697361

This list has a handful of items that need to have the links manually fixed.

**Comment by Ziiiiing** [comment]
While updating replacement links for items in the spreadsheet, I found one with ID `76b7a0c6-1a74-45ef-856a-712b9e5fe958` is **Active** but **unpublished** on GEOMG.
