### ISSUE TITLE
Finish MN Plats Index Map

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/metadata#31]
We did not finish this as many townships have multiple plats for the same area.  To solve this, use a search string in the access/website link. Example https://geo.btaa.org/?search_field=all_fields&q=T027N+R22W

The thumbnail images are also too large. Maybe remove for now?

**Comment by Ziiiiing** [comment]
see index map here: https://github.com/Ziiiiing/index-map-v2/blob/main/mn_township_index_map.geojson
