### ISSUE TITLE
Parse XML for MSU Important Farmland Maps

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/metadata#32]
- [x] Convert this info to a spreadsheet https://drive.google.com/file/d/1qeoKhdyQRJQ_NxZ8BjugCOVUGuGz-9dx/view?usp=sharing
- [x] Transform to the Aardvark schema

**Comment by karenmajewicz** [comment]
Member Of: 2787a9e8-0bef-452e-9e5f-e83042c193b4| 64bd8c4c-8e60-4956-b43d-bdc3f93db488
Is Part Of: 06d-02
Code: 6d-02

**Comment by Ziiiiing** [comment]
- Here's the Repo stores the parsing script: https://github.com/BTAA-Geospatial-Data-Project/parse-xml/tree/main/MSU_Important_Farmland_Maps

- Metadata(Aardvark) spreadsheet can be found here: https://docs.google.com/spreadsheets/d/1dlhhL1HAoN-9yBmmh10mR4PnwoOAmQmd1kLa0W6DVZc/edit?usp=sharing
