### ISSUE TITLE
Add Wisconsin LiDAR 2022 records

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/metadata#6]

**Comment by karenmajewicz** [comment]
[New_LiDAR_2022.zip](https://github.com/BTAA-Geospatial-Data-Project/metadata/files/8062240/New_LiDAR_2022.zip)

**Comment by karenmajewicz** [comment]
- [ ] convert to spreadsheet
- [ ] convert to Aardvark
- [ ] upload to GEOMG
- [ ] ping Karen for final edits

**Comment by Ziiiiing** [comment]
Use the [schema_update.py](https://github.com/BTAA-Geospatial-Data-Project/GBL-Schema-Update/blob/main/schema_update.py) along with the [crosswalk.csv](https://github.com/BTAA-Geospatial-Data-Project/GBL-Schema-Update/blob/main/crosswalk.csv) from the same repository to convert JSONs to **Aardvark** version.

Here's the updated JSONs with Aardvark schema
[aardvark.zip](https://github.com/BTAA-Geospatial-Data-Project/metadata/files/8151622/aardvark.zip)

**Comment by karenmajewicz** [comment]
finished here: https://geo.btaa.org/?f%5Bdct_spatial_sm%5D%5B%5D=Wisconsin&q=2022-03-07&search_field=all_fields
